---
name: greeter

releases:
- name: greeter-release
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  canary_watch_time: 30000
  update_watch_time: 30000
  max_in_flight: 1
  max_errors: 1

instance_groups:
- name: router
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: router
    release: greeter-release
    properties:
      upstreams: 10.0.31.191

- name: app
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: default
  networks:
  - name: default
    static_ips:
    - 10.0.31.191
  jobs:
  - name: app
    release: greeter-release
    properties: {}
